main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='main.home'),
    path('login', views.login_page, name='main.login'),
    path('logout', views.logout_view, name='main.logout'),
    path('checkuser', views.check_user, name='main.checkuser'),
    path('verifyuser', views.verify_user, name='main.verifyuser')
]

sisrapsur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('administrador/', include('main.urls_administrador')),
    path('secretaria/', include('main.urls_secretaria')),
    path('afiliado/', include('afiliados.urls_afiliado')),
    path('automovil/', include('afiliados.urls_automovil')),
    path('horario/', include('secretarias.urls_horario')),
    path('ventas/', include('ventas.urls')),
    path('reportes/', include('reportes.urls')),
    path('admin/backups/', include('dbbackup_ui.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secretarias/models.py
import datetime
from django.db import models
from main.models import Secretaria


class Horario(models.Model):
    turno = models.CharField(max_length=30, unique=True)
    hora_ingreso = models.TimeField()
    hora_salida = models.TimeField()


class AsignacionHorario(models.Model):
    fecha = models.DateField()
    hora_ingreso_reg = models.TimeField(blank=True, null=True)
    hora_salida_reg = models.TimeField(blank=True, null=True)
    hora_ingreso = models.TimeField()
    hora_salida = models.TimeField()
    horario = models.ForeignKey(Horario, on_delete=models.CASCADE)
    empleado = models.ForeignKey(Secretaria, on_delete=models.CASCADE, related_name='asignaciones')
    id_suplente = models.IntegerField(default=0)

secretarias/forms.py
from django import forms
from django.forms import ModelForm, TextInput, ValidationError
from .models import Horario
from main.models import Usuario
from django.contrib.auth import authenticate


class HorarioForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk is not None:
            self.fields['turno'].widget.attrs.update({'readonly': True})

    class Meta:
        model = Horario
        fields = ['turno', 'hora_ingreso', 'hora_salida']
        widgets = {
            'turno': TextInput(attrs={'class': 'form-control upper'}),
            'hora_ingreso': TextInput(attrs={'class': 'form-control clockpicker'}),
            'hora_salida': TextInput(attrs={'class': 'form-control clockpicker'}),
        }


class SuplenciaForm(forms.Form):
    current_user = forms.CharField(widget=forms.HiddenInput)
    current_huella = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'disabled': True}))
    current_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                         'style': 'margin-top: 10px'}))

    alt_user = forms.CharField(widget=forms.HiddenInput)
    alt_huella = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'disabled': True}))
    alt_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                     'style': 'margin-top: 10px'}))

    def clean_current_password(self):
        password = self.cleaned_data.get('current_password')
        user = self.get_current_user()
        if user is None:
            raise ValidationError('Credenciales incorrectas.')
        return password

    def clean_alt_password(self):
        password = self.cleaned_data.get('alt_password')
        user = self.get_alt_user()
        if user is None:
            raise ValidationError('Credenciales incorrectas.')
        return password

    def get_current_user(self):
        username = self.cleaned_data.get('current_user')
        password = self.cleaned_data.get('current_password')
        huella = self.cleaned_data.get('current_huella')
        return self.get_user(username, password, huella)

    def get_alt_user(self):
        username = self.cleaned_data.get('alt_user')
        password = self.cleaned_data.get('alt_password')
        huella = self.cleaned_data.get('alt_huella')
        return self.get_user(username, password, huella)

    def get_user(self, username, password, huella):
        user = authenticate(usuario=username, password=password)
        if user is None:
            try:
                user = Usuario.objects.get(usuario=username, codigo_huella=huella)
                return user
            except (Usuario.DoesNotExist, Usuario.MultipleObjectsReturned) as e:
                return None
        return user


class SuplenteForm(forms.Form):
    current_user_id = forms.CharField(widget=forms.HiddenInput)
    usuario = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_usuario(self):
        user_id = self.cleaned_data.get('current_user_id')
        nombre = self.cleaned_data.get('usuario')
        try:
            user = Usuario.objects.get(usuario=nombre)
        except (Usuario.DoesNotExist, Usuario.MultipleObjectsReturned) as e:
            user = None
        if user is None:
            raise ValidationError('Usuario inexistente o credenciales incorrectas.')
        if str(user_id) == str(user.id):
            raise ValidationError('El mismo usuario no puede hacer suplencia')
        if not (hasattr(user, 'afiliado') or hasattr(user, 'secretaria')):
            raise ValidationError('Solo un afiliado u otra secretaria puede hacer suplencia')
        return nombre

    def get_suplente(self):
        nombre = self.cleaned_data.get('usuario')
        user = Usuario.objects.get(usuario=nombre)
        return user

secretarias/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.http import JsonResponse
from .models import Horario, AsignacionHorario
from main.models import Persona, Usuario
from .forms import HorarioForm, SuplenciaForm, SuplenteForm
import datetime


class HorarioList(ListView):
    model = Horario
    template_name = 'horario/lista.html'


def horario_crear(request):
    if request.method == 'POST':
        form = HorarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('horario.lista')
    else:
        form = HorarioForm()
    return render(request, 'horario/form.html', {'form': form})


def horario_editar(request, pk):
    horario = get_object_or_404(Horario, pk=pk)
    if request.method == 'POST':
        form = HorarioForm(request.POST, instance = horario)
        if form.is_valid():
            form.save()
            return redirect('horario.lista')
    else:
        form = HorarioForm(instance = horario)
    return render(request, 'horario/form.html', {'form': form})


def horario_eliminar(request, pk):
    horario = get_object_or_404(Horario, pk=pk)
    horario.delete()
    return JsonResponse({'success': True})


def horario_mostrar(request):
    ci = request.GET.get('ci', '')
    inicio = request.GET.get('inicio', '')
    fin = request.GET.get('fin', '')
    try:
        persona = Persona.objects.get(ci=ci)
    except Persona.DoesNotExist:
        return JsonResponse({'success': False, 'message': 'No existen secretarias con este ci'})
    if not (hasattr(persona, 'usuario') and hasattr(persona.usuario, 'secretaria')):
        return JsonResponse({'success': False, 'message': 'No existen secretarias con este ci'})
    nombre = persona.nombres + ' ' + persona.apellidos
    turnos = []
    secretaria = persona.usuario.secretaria
    for asig in secretaria.asignaciones.filter(fecha__range=(inicio, fin)):
        newT = {
                'id': asig.id,
                'title': asig.horario.turno,
                'start': "%sT%s" % (asig.fecha.strftime("%Y-%m-%d"), asig.hora_ingreso.strftime("%H:%M")),
                'end': "%sT%s" % (asig.fecha.strftime("%Y-%m-%d"), asig.hora_salida.strftime("%H:%M")),
                'color': 'green'
                }
        turnos.append(newT)
    return JsonResponse({'success': True, 'nombre': nombre, 'turnos': turnos})


def asignacion_eliminar(request):
    id = request.GET.get('id', 0)
    asig = get_object_or_404(AsignacionHorario, pk=id)
    asig.delete()
    return JsonResponse({'success': True})


def asignacion_crear(request):
    ci = request.GET.get('ci', '')
    fecha = request.GET.get('fecha', '')
    id_horario = request.GET.get('id_horario', 0)
    horario = Horario.objects.get(pk=id_horario)
    persona = Persona.objects.get(ci=ci)
    secretaria = persona.usuario.secretaria
    flag = False
    try:
        current = AsignacionHorario.objects.filter(empleado__lugar=secretaria.lugar, fecha=fecha, horario=horario).get()
        return JsonResponse({'message':'Ya existe un empleado asignado a este turno', 'success': False})
    except AsignacionHorario.DoesNotExist:
        flag = True
    asignacion = AsignacionHorario(empleado=secretaria, fecha=fecha, horario=horario, hora_ingreso=horario.hora_ingreso, hora_salida=horario.hora_salida)
    asignacion.save()
    return JsonResponse({'success': True})


def turnos(request):
    context = {'horarios': Horario.objects.all()}
    return render(request, 'turnos/turnos.html', context)


def suplente(request):
    form = SuplenteForm(initial={'current_user_id': request.user.id})
    if request.method == 'POST':
        form = SuplenteForm(request.POST)
        if form.is_valid():
            suplente = form.get_suplente()
            return redirect('secretaria.suplente.delegar', sup_pk=suplente.id)
    return render(request, 'suplencia.html', {'form': form})


def delegar_suplencia(request, sup_pk):
    current_user = request.user
    alt_user = Usuario.objects.get(pk=sup_pk)
    form = SuplenciaForm(initial={
        'current_user': current_user.usuario,
        'current_huella': current_user.codigo_huella,
        'alt_user': alt_user.usuario,
        'alt_huella': alt_user.codigo_huella
    })
    if request.method == 'POST':
        form = SuplenciaForm(request.POST)
        if form.is_valid():
            asignaciones = current_user.secretaria.asignaciones.filter(fecha=datetime.date.today())
            if asignaciones.exists():
                asig = asignaciones[0]
                asig.id_suplente = alt_user.pk
                asig.save()
            return redirect('/')
    return render(request, 'delegar_suplente.html', {'form': form, 'current': current_user.usuario, 'alt': alt_user.usuario})

secretarias/templates/delegar_suplente.html
{% extends "main_layout.html" %}

{% block styles%}
{% load static%}
{% endblock %}

{% block main_title %}
Delegar suplente
{% endblock %}

{% block content  %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a href="#" ><i class="fa fa-wrench"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <h4>Ingrese credenciales para realizar la suplencia</h4>
                <style>
                    .well{
                        cursor: pointer
                    }
                    .well-selected{
                        background: LightBlue
                    }
                </style>
                <form class="form-horizontal" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xs-3 col-xs-offset-2 well well-sm">
                            <div class="text-center"  style="margin-bottom: 10px">
                                <h4 style="margin-top: 0">{{current}}</h4>
                                <div class="fa-stack fa-5x">
                                    <i class="fas fa-fingerprint fa-stack-2x"></i>
                                </div>
                                {{form.current_user}}
                                {{form.current_huella}}
                                {{form.current_password}}
                                {% if form.current_password.errors %}
                                <span class="text-danger">{{form.current_password.errors|first}}</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-xs-3 col-xs-offset-2 well well-sm">
                            <div class="text-center"  style="margin-bottom: 10px;">
                                <h4 style="margin-top: 0">{{alt}}</h4>
                                <div class="fa-stack fa-5x">
                                    <i class="fas fa-fingerprint fa-stack-2x"></i>
                                </div>
                                {{form.alt_user}}
                                {{form.alt_huella}}
                                {{form.alt_password}}
                                {% if form.alt_password.errors %}
                                <span class="text-danger">{{form.alt_password.errors|first}}</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    {{form.errors}}
                    <div class="form-group">
                        <div class="col-xs-offset-3 col-xs-6">
                            <a href="{% url 'secretaria.suplente' %}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Volver</a>
                            <button type="submit" class="btn btn-primary pull-right">
                                <i class="fa fa-check"></i> Reemplazo
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
{% load static %}
<script>
    $(function(){
        var alt_huella = $("#id_alt_huella").val();
        var current_huella = $("#id_current_huella").val();
        if(current_huella.length>0){
            $("#id_current_password").hide();
        }
        if(alt_huella.length>0){
            $("#id_alt_password").hide();
        }
    });

    $(function(){
        var ws;

        $('.well').on('click', function(){
            $(".well").removeClass('well-selected');
            $(this).addClass('well-selected');
            openConnection();
        });

        function openConnection(){
            closeConnection();
            var fingerprint = $(".well-selected").find("#id_current_huella, #id_alt_huella").eq(0).val();
            if(fingerprint){
                ws = new WebSocket("ws://localhost:9090/finger/finger");
                ws.onopen = function(){
                    console.log("ws connection open...");
                    var data = {
                        type: "prepare-verify",
                        data: fingerprint
                    };
                    ws.send(JSON.stringify(data));
                };

                ws.onmessage = function(evt){
                    var response = JSON.parse(evt.data);
                    var type = response.type;
                    //console.log(response);
                    switch(type){
                        case 'verify-response':
                            $(".well-selected .fa-stack").find("i.fa-check, i.fa-close").remove();
                            var success = response.success;
                            var $icon = $("<i class='fas fa-check fa-stack-1x' style='color:green'></i>").hide();
                            if(success){
                                $(".well-selected .fa-stack").append($icon);
                                $(".well-selected").find("#id_current_huella, #id_alt_huella").prop("disabled", false);
                                checkFormForSubmit();
                            }else{
                                $icon = $("<i class='fas fa-close fa-stack-1x' style='color:red'></i>").hide();
                                $(".well-selected .fa-stack").append($icon);
                                $(".well-selected").find("#id_current_huella, #id_alt_huella").prop("disabled", true);
                                openConnection();
                            }
                            $icon.show('fast');
                        break;
                    }
                }
            }
        }

        function closeConnection(){
            if(ws)
                ws.close();
        }

        function checkFormForSubmit(){
            var flag = true;
            $("form").find(".fa-stack").each(function(){
                var $item = $(this);
                if($item.find(".fa-check").length == 0)
                    flag = false;
            });
            if(flag)
                $("form").submit();
        }
    });
</script>
{% endblock %}

secretarias/templates/suplencia.html
{% extends "main_layout.html" %}

{% block styles%}
{% load static%}
{% endblock %}

{% block main_title %}
Delegar suplente
{% endblock %}

{% block content  %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a href="#" ><i class="fa fa-wrench"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <h4>Ingrese usuario para suplencia</h4>
                <form class="form-horizontal" method="POST">
                    {% csrf_token %}
                    {{form.current_user_id}}
                    <div class="form-group">
                        <label for="{{form.usuario.id_for_label}}" class="control-label col-xs-3">USUARIO *</label>
                        <div class="col-xs-6">
                            {{form.usuario}}
                            {% if form.usuario.errors %}
                            <span class="text-danger">{{form.usuario.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-xs-offset-3 col-xs-6">
                            <button type="submit" class="btn btn-primary pull-right">
                                <i class="fa fa-arrow-right"></i> Siguiente
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
{% load static %}
{% endblock %}