main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='main.home'),
    path('login', views.login_page, name='main.login'),
    path('logout', views.logout_view, name='main.logout'),
    path('checkuser', views.check_user, name='main.checkuser'),
    path('verifyuser', views.verify_user, name='main.verifyuser')
]

sisrapsur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('administrador/', include('main.urls_administrador')),
    path('secretaria/', include('main.urls_secretaria')),
    path('afiliado/', include('afiliados.urls_afiliado')),
    path('automovil/', include('afiliados.urls_automovil')),
    path('horario/', include('secretarias.urls_horario')),
    path('ventas/', include('ventas.urls')),
    path('reportes/', include('reportes.urls')),
    path('admin/backups/', include('dbbackup_ui.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

afiliados/models.py
import uuid
from os import path
from django.db import models
from main.models import Afiliado


def content_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (str(uuid.uuid4().hex), ext)
    return path.join('fotos_vehiculos', filename)


class Automovil(models.Model):
    placa = models.CharField(max_length=10, unique=True)
    marca = models.CharField(max_length=30)
    tipo = models.CharField(max_length=30)
    clase = models.CharField(max_length=30)
    plazas = models.IntegerField(default=0)
    color = models.CharField(max_length=30)
    foto = models.ImageField(upload_to=content_filename)
    conductor = models.OneToOneField(Afiliado, on_delete=models.SET_NULL, blank=True, null=True)

main/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import MinLengthValidator, MinValueValidator


class UsuarioManager(BaseUserManager):
    def create_user(self, usuario, password=None):
        if not usuario:
            raise ValueError('Es necesario definir un nombre de usuario')

        user = self.model(
            usuario=usuario
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, usuario, password):
        user = self.create_user(
            usuario,
            password=password
        )
        user.tipo = 'ADMINISTRADOR'
        user.is_superuser = True
        user.save(using=self._db)
        admin = Administrador(usuario=user)
        admin.save(using=self._db)
        persona = Persona(ci=usuario, nombres='admin', apellidos='admin', direccion='admin#12', telefono='0000000', usuario=user)
        persona.save(using=self._db)
        return user


class Usuario(AbstractBaseUser):
    tipo_opciones = (
        ('ADMINISTRADOR', 'ADMINISTRADOR'),
        ('SECRETARIA', 'SECRETARIA'),
        ('AFILIADO', 'AFILIADO')
    )
    usuario = models.CharField(max_length=50, unique=True, error_messages={'unique': 'El valor ya ha sido tomado'})
    codigo_huella = models.TextField(blank=True, null=True)
    tipo = models.CharField(max_length=15, choices=tipo_opciones, default='AFILIADO')
    activo = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    USERNAME_FIELD = 'usuario'
    objects = UsuarioManager()
    #REQUIRED_FIELDS = ['']

    def __str__(self):
        return self.usuario

    def has_perm(self, perm, obj=None):
        "Tiene permisos especificos?"
        return True

    def has_module_perms(self, app_label):
        "Permisos en `app_label`?"
        return True

    def get_turno(self):
        if not hasattr(self, 'secretaria'):
            return None
        asignaciones = self.secretaria.asignaciones.filter(fecha=datetime.date.today(),
                                                           hora_ingreso__lte=datetime.datetime.now(),
                                                           hora_salida__gte=datetime.datetime.now())
        if asignaciones.exists():
            asig = asignaciones[0]
            return asig
        return None

    def get_reemplazo(self):
        asig = self.get_turno()
        if asig is None:
            return None
        try:
            altern = Usuario.objects.get(pk=asig.id_suplente)
        except (Usuario.DoesNotExist, Usuario.MultipleObjectsReturned) as e:
            return None
        return altern


class Persona(models.Model):
    ci = models.CharField(max_length=15, unique=True, validators=[MinLengthValidator(7, 'El minimo de caracteres admitidos es de 7')])
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100)
    telefono = models.IntegerField(validators=[MinValueValidator(6000000, 'El numero de telefono no puede ser tan corto.')])
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)


class Lugar(models.Model):
    nombre = models.CharField(max_length=15, unique=True)
    codigo = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return self.nombre


class Afiliado(models.Model):
    estados = (
        ('HABILITADO', 'HABILITADO'),
        ('SIN ENVIOS', 'SIN ENVIOS'),
        ('LICENCIA', 'LICENCIA'),
        ('SUSPENDIDO', 'SUSPENDIDO'),
    )
    estado = models.CharField(max_length=15, choices=estados, default='HABILITADO')
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)


class Secretaria(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    lugar = models.ForeignKey(Lugar, on_delete=models.CASCADE)


class Administrador(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)

afiliados/forms.py
from django.forms import ModelForm, TextInput, FileInput
from .models import Automovil


class AutomovilForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk is not None:
            self.fields['placa'].widget.attrs.update({'readonly': True})

    class Meta:
        model = Automovil
        fields = ['placa', 'marca', 'tipo', 'clase', 'plazas', 'color', 'foto']
        widgets = {
            'placa': TextInput(attrs={'class': 'form-control upper'}),
            'marca': TextInput(attrs={'class': 'form-control upper'}),
            'tipo': TextInput(attrs={'class': 'form-control upper'}),
            'clase': TextInput(attrs={'class': 'form-control upper'}),
            'plazas': TextInput(attrs={'class': 'form-control upper only-numbers'}),
            'color': TextInput(attrs={'class': 'form-control upper'}),
            'foto': FileInput(attrs={'class': 'form-control'})
        }

afiliados/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.http import JsonResponse
from django.db import transaction
from .forms import AutomovilForm
from main.forms import UsuarioForm, PersonaForm
from .models import Automovil
from main.models import Afiliado, Persona


class AutomovilList(ListView):
    model = Automovil
    template_name = 'automovil/lista.html'


class AutomovilDetail(DetailView):
    model = Automovil
    template_name = 'automovil/detalle.html'


def automovil_crear(request):
    if request.method == 'POST':
        form = AutomovilForm(request.POST, request.FILES)
        if form.is_valid():
            auto = form.save()
            return redirect('automovil.mostrar', pk=auto.id)
    else:
        form = AutomovilForm()
    return render(request, 'automovil/form.html', {'form': form})


def automovil_editar(request, pk):
    automovil = get_object_or_404(Automovil, pk=pk)
    if request.method == 'POST':
        form = AutomovilForm(request.POST, request.FILES, instance=automovil)
        if form.is_valid():
            auto = form.save()
            return redirect('automovil.mostrar', pk=auto.id)
    else:
        form = AutomovilForm(instance=automovil)
    return render(request, 'automovil/form.html', {'form': form})


def automovil_eliminar(request, pk):
    automovil = get_object_or_404(Automovil, pk=pk)
    automovil.delete()
    return JsonResponse({'success': True})


def automovil_link(request, pk):
    automovil = get_object_or_404(Automovil, pk=pk)
    ligar = request.POST['ligar']
    ci = request.POST['ci']
    if ligar == 'true':
        try:
            persona = Persona.objects.get(ci=ci)
        except (Persona.DoesNotExist, Persona.MultipleObjectsReturned) as e:
            persona = None
        if persona is None:
            return JsonResponse({'error': 'No se ha encontrado afiliado con este ci', 'success': False})
        usuario = persona.usuario
        if not hasattr(usuario, 'afiliado'):
            return JsonResponse({'error': 'La persona con este ci no es afiliado', 'success': False})
        afiliado = usuario.afiliado
        if hasattr(afiliado, 'automovil'):
            return JsonResponse({'error': 'Este afiliado ya esta vinculado a un vehiculo', 'success': False})
        automovil.conductor = afiliado
        automovil.save()
        return JsonResponse({'success': True})
    else:
        print("desligando")
        automovil.conductor = None
        automovil.save()
        return JsonResponse({'success': True})


# Vistas para secretarias
class AfiliadoList(ListView):
    model = Afiliado
    template_name = 'afiliado/lista.html'


@transaction.atomic
def afiliado_crear(request):
    if request.method == 'POST':
        user_form = UsuarioForm(request.POST)
        pers_form = PersonaForm(request.POST)
        if user_form.is_valid() and pers_form.is_valid():
            user = user_form.save(commit=False)
            user.tipo = 'AFILIADO'
            user.save()
            persona = pers_form.save(commit=False)
            persona.usuario = user
            persona.save()
            afili = Afiliado(usuario = user)
            afili.save()
            return redirect('afiliado.lista')
    else:
        user_form = UsuarioForm()
        pers_form = PersonaForm()
    return render(request, 'afiliado/crear.html', {'user_form': user_form, 'pers_form': pers_form})


@transaction.atomic
def afiliado_editar_datos(request, pk):
    afiliado = get_object_or_404(Afiliado, pk=pk)
    usuario = afiliado.usuario
    persona = usuario.persona
    if request.method == 'POST':
        form = PersonaForm(request.POST, instance = persona)
        if form.is_valid():
            form.save()
            return redirect('afiliado.lista')
    else:
        form = PersonaForm(instance = persona)
    return render(request, 'afiliado/editar_datos.html', {'pers_form': form})


@transaction.atomic
def afiliado_editar_credenciales(request, pk):
    afiliado = get_object_or_404(Afiliado, pk=pk)
    usuario = afiliado.usuario
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance = usuario)
        if form.is_valid():
            form.save()
            return redirect('afiliado.lista')
    else:
        form = UsuarioForm(instance = usuario)
    return render(request, 'afiliado/editar_credenciales.html', {'user_form': form})


@transaction.atomic
def afiliado_eliminar(request, pk):
    afiliado = get_object_or_404(Afiliado, pk=pk)
    usuario = afiliado.usuario
    usuario.delete()
    return JsonResponse({'success': True})


def afiliado_cambiar_estado(request):
    if request.method == 'POST':
        pk = request.POST["pk"]
        nuevo_estado = request.POST['estado']
        afiliado = get_object_or_404(Afiliado, pk=pk)
        afiliado.estado = nuevo_estado
        afiliado.save()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})


class AfiliadoEstado(ListView):
    model = Afiliado
    template_name = 'afiliado/estado.html'

afiliados/templates/afiliado/crear.html
{% extends "main_layout.html" %}

{% block main_title %}
Crear afiliado
{% endblock %}

{% block content  %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a href="#" ><i class="fa fa-wrench"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form class="form-horizontal" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{user_form.usuario.id_for_label}}" class="control-label col-xs-3">USUARIO *</label>
                        <div class="col-xs-6">
                            {{user_form.usuario}}
                            {% if user_form.usuario.errors %}
                            <span class="text-danger">{{user_form.usuario.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{user_form.password1.id_for_label}}" class="control-label col-xs-3">CONTRASEÑA *</label>
                        <div class="col-xs-6">
                            {{user_form.password1}}
                            {% if user_form.password1.errors %}
                            <span class="text-danger">{{user_form.password1.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{user_form.password2.id_for_label}}" class="control-label col-xs-3">REPETIR CONTRASEÑA *</label>
                        <div class="col-xs-6">
                            {{user_form.password2}}
                            {% if user_form.password2.errors %}
                            <span class="text-danger">{{user_form.password2.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="{{pers_form.ci.id_for_label}}" class="control-label col-xs-3">CI *</label>
                        <div class="col-xs-6">
                            {{pers_form.ci}}
                            {% if pers_form.ci.errors %}
                            <span class="text-danger">{{pers_form.ci.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{pers_form.nombres.id_for_label}}" class="control-label col-xs-3">NOMBRES *</label>
                        <div class="col-xs-6">
                            {{pers_form.nombres}}
                            {% if pers_form.nombres.errors %}
                            <span class="text-danger">{{pers_form.nombres.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{pers_form.apellidos.id_for_label}}" class="control-label col-xs-3">APELLIDOS *</label>
                        <div class="col-xs-6">
                            {{pers_form.apellidos}}
                            {% if pers_form.apellidos.errors %}
                            <span class="text-danger">{{pers_form.apellidos.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{pers_form.direccion.id_for_label}}" class="control-label col-xs-3">DIRECCION *</label>
                        <div class="col-xs-6">
                            {{pers_form.direccion}}
                            {% if pers_form.direccion.errors %}
                            <span class="text-danger">{{pers_form.direccion.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{pers_form.telefono.id_for_label}}" class="control-label col-xs-3">TELEFONO *</label>
                        <div class="col-xs-6">
                            {{pers_form.telefono}}
                            {% if pers_form.telefono.errors %}
                            <span class="text-danger">{{pers_form.telefono.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="fingerprint" class="control-label col-xs-3">HUELLA DIGITAL</label>
                        <div class="col-xs-6">
                            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-fingerprint" id="show-finger-modal">
                                <i class="fas fa-fingerprint"></i>
                                Cargar huella
                            </button>
                            {{user_form.codigo_huella}}
                            {% if user_form.codigo_huella.errors %}
                            <span class="text-danger">{{user_form.codigo_huella.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-xs-offset-3 col-xs-6">
                            <div class="pull-right">
                                <a href="{% url 'afiliado.lista' %}" class="btn btn-default">
                                    <i class="fa fa-arrow-left"></i> Volver
                                </a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-save"></i> Guardar
                                </button>
                            </div>
                        </div>
                    </div>
                </form> 
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-fingerprint">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Cargar huella</h4>
      </div>
      <div class="modal-body">
          <div class="row">
              <div class="col-xs-12 text-center">
                  <span id="fingerprint-messages"></span>
              </div>
          </div>
          <div class="row">
              <div class="col-xs-12">
                    <div id="fingerprint-status" class="text-center">
                        <span class="fa-stack fa-4x" id="fingerprint-icon">
                          <i class="fas fa-fingerprint fa-stack-2x"></i>
                          <i class="fas fa-check fa-stack-2x hide" id="icon-correct" style="color: green"></i>
                          <i class="fas fa-close fa-stack-2x hide" id="icon-incorrect" style="color: red"></i>
                        </span>
                          <i class="fas fa-circle fa-3x"></i>
                          <i class="fas fa-circle fa-3x"></i>
                          <i class="fas fa-circle fa-3x"></i>
                          <i class="fas fa-circle fa-3x"></i>
                    </div>
              </div>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock  %}

{% block scripts %}
<script>
    $(function(){
        var ws;
        checkFingerPrintExistence();
        $("#modal-fingerprint").on("show.bs.modal", function(){
            openConnection();
        });

        $("#modal-fingerprint").on("hide.bs.modal", function(){
            closeConnection();
        });

        function openConnection(){
            ws = new WebSocket("ws://localhost:9090/finger/finger");
            ws.onopen = function(){
                console.log("ws connection open...");
                reset();
                var data = {
                    type: "prepare-register"
                };
                ws.send(JSON.stringify(data));
            };

            ws.onmessage = function(evt){
                var response = JSON.parse(evt.data);
                var type = response.type;
                //console.log(response);
                switch(type){
                    case 'reader-not-found':
                        $("#fingerprint-icon").addClass("text-danger");
                        $("#fingerprint-messages").addClass("text-danger").text(response.message);
                    break;
                    case 'fingerprint-success':
                        var checkNumber = response.remainder;
                        var totalCircles = 3;
                        $("#fingerprint-status>i").eq(totalCircles-response.remainder).toggleClass("fa-circle fa-check-circle");
                    break;
                    case 'register-success':
                        $("#fingerprint-icon #icon-correct").removeClass("hide");
                        $("#id_codigo_huella").val(response.template_data);
                        checkFingerPrintExistence();
                    break;
                    case 'bad-image':
                        $("#fingerprint-icon").addClass("text-danger");
                        $("#fingerprint-icon #icon-incorrect").removeClass("hide");
                        $("#fingerprint-messages").addClass("text-danger").text(response.message);
                        var $span_ref = $("<span> Cierre esta ventana para intentar nuevamente.</span>")
                        $("#fingerprint-messages").append($span_ref);
                        $("#id_codigo_huella").val("");
                        checkFingerPrintExistence();
                    break;
                }
            }

            ws.onclose = function(){
                console.log("ws connection closed");
            }
        }

        function closeConnection(){
            ws.close();
        }

        function reset(){
            $("#fingerprint-icon").removeClass("text-danger");
            $("#fingerprint-messages").removeClass("text-danger").text("");
            $("#fingerprint-status>i").removeClass("fa-check-circle").addClass("fa-circle");
            $("#fingerprint-status #icon-correct").addClass("hide");
            $("#fingerprint-status #icon-incorrect").addClass("hide");
        }

        function checkFingerPrintExistence(){
            var fingerprint = $("#id_codigo_huella").val();
            $("#show-finger-modal").find(".fa-check").remove();
            if(fingerprint.length>0){
                var $check = $("<i class='fas fa-check' style='color: red'></i>");
                $("#show-finger-modal").find("fa-check").remove();
                $("#show-finger-modal").append($check);
            }
        }
    });
</script>
{% endblock %}

afiliados/templates/afiliado/editar_datos.html
{% extends "main_layout.html" %}

{% block main_title %}
Modificar datos personales <small>(Afiliado)</small>
{% endblock %}

{% block content  %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a href="#" ><i class="fa fa-wrench"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form class="form-horizontal" method="POST">
                    {% csrf_token %}
                
                    <div class="form-group">
                        <label for="{{pers_form.ci.id_for_label}}" class="control-label col-xs-3">CI *</label>
                        <div class="col-xs-6">
                            {{pers_form.ci}}
                            {% if pers_form.ci.errors %}
                            <span class="text-danger">{{pers_form.ci.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{pers_form.nombres.id_for_label}}" class="control-label col-xs-3">NOMBRES *</label>
                        <div class="col-xs-6">
                            {{pers_form.nombres}}
                            {% if pers_form.nombres.errors %}
                            <span class="text-danger">{{pers_form.nombres.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{pers_form.apellidos.id_for_label}}" class="control-label col-xs-3">APELLIDOS *</label>
                        <div class="col-xs-6">
                            {{pers_form.apellidos}}
                            {% if pers_form.apellidos.errors %}
                            <span class="text-danger">{{pers_form.apellidos.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{pers_form.direccion.id_for_label}}" class="control-label col-xs-3">DIRECCION *</label>
                        <div class="col-xs-6">
                            {{pers_form.direccion}}
                            {% if pers_form.direccion.errors %}
                            <span class="text-danger">{{pers_form.direccion.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{pers_form.telefono.id_for_label}}" class="control-label col-xs-3">TELEFONO *</label>
                        <div class="col-xs-6">
                            {{pers_form.telefono}}
                            {% if pers_form.telefono.errors %}
                            <span class="text-danger">{{pers_form.telefono.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-xs-offset-3 col-xs-6">
                            <div class="pull-right">
                                <a href="{% url 'afiliado.lista' %}" class="btn btn-default">
                                    <i class="fa fa-arrow-left"></i> Volver
                                </a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-save"></i> Guardar
                                </button>
                            </div>
                        </div>
                    </div>
                </form> 
            </div>
        </div>
    </div>
</div>
{% endblock  %}