main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='main.home'),
    path('login', views.login_page, name='main.login'),
    path('logout', views.logout_view, name='main.logout'),
    path('checkuser', views.check_user, name='main.checkuser'),
    path('verifyuser', views.verify_user, name='main.verifyuser')
]

sisrapsur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('administrador/', include('main.urls_administrador')),
    path('secretaria/', include('main.urls_secretaria')),
    path('afiliado/', include('afiliados.urls_afiliado')),
    path('automovil/', include('afiliados.urls_automovil')),
    path('horario/', include('secretarias.urls_horario')),
    path('ventas/', include('ventas.urls')),
    path('reportes/', include('reportes.urls')),
    path('admin/backups/', include('dbbackup_ui.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ventas/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('dosificaciones', views.dosificaciones, name='dosificacion.lista'),
    path('dosificaciones/crear', views.dosificaciones_crear, name='dosificacion.crear'),
    path('dosificaciones/cambiar', views.dosificacion_activar, name='dosificacion.cambiar'),
    path('boleto', views.venta_boleto, name='ventas.boleto'),
    path('factura/<int:pk>', views.factura_mostrar, name='factura.mostrar'),
    path('envios', views.venta_envios, name='ventas.envio'),
    path('envios-recibido/<int:pk>', views.envio_recibido, name='envio.recibido'),
    path('detalle/<int:pk>', views.VentaDetail.as_view(), name='ventas.detalle'),
    path('lista-envios', views.lista_envios, name='lista.envios'),
    path('get-cliente', views.get_cliente, name='ventas.clientes'),
    path('get-usuario', views.get_usuario, name='lista.get_usuario'),
    path('lista-conductores', views.lista_conductores, name='ventas.lista_conductores'),
    path('lista-conductores/orden', views.lista_orden, name='lista.orden'),
    path('lista-conductores/cargar', views.lista_cargar, name='lista.cargar'),
    path('lista-conductores/agregar', views.lista_agregar, name='lista.agregar'),
    path('lista-conductores/eliminar/<int:pk>', views.lista_eliminar, name='lista.delete')
]

ventas/models.py
import datetime
from django.db import models
from main.models import Afiliado, Lugar, Secretaria
from afiliados.models import Automovil


class Lista(models.Model):
    fecha = models.DateField(default=datetime.date.today)
    automovil = models.ForeignKey(Automovil, on_delete=models.CASCADE)
    afiliado = models.ForeignKey(Afiliado, on_delete=models.CASCADE)
    hora_entrada = models.TimeField(default=datetime.datetime.now)
    hora_salida = models.TimeField(null=True, blank=True)
    orden = models.IntegerField(default=1)
    activo = models.BooleanField(default=True)
    origen = models.CharField(max_length=15)
    destino = models.CharField(max_length=15)


class Cliente(models.Model):
    ci_nit = models.CharField(max_length=10, unique=True)
    nombre = models.CharField(max_length=50)
    cel = models.IntegerField()


class Venta(models.Model):
    tipos = (
        ('ENVIO', 'ENVIO'),
        ('BOLETO', 'BOLETO')
    )

    fecha_hora = models.DateTimeField(default=datetime.datetime.now)
    tipo = models.CharField(choices=tipos, default='BOLETO', max_length=15)
    origen = models.CharField(max_length=15)
    destino = models.CharField(max_length=15)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    total = models.FloatField(default=0)
    lista = models.ForeignKey(Lista, on_delete=models.CASCADE)
    responsable = models.ForeignKey(Secretaria, on_delete=models.CASCADE)
    responsable_sup = models.IntegerField(default=0, blank=True, null=True)


class Envio(models.Model):
    tipos = (
        ('GIRO', 'GIRO'),
        ('SOBRE', 'SOBRE'),
        ('PAQUETE', 'PAQUETE'),
        ('CAJA', 'CAJA'),
        ('BOLSA', 'BOLSA'),
        ('OTROS', 'OTROS'),
    )

    pagos = (
        ('PAGADO', 'PAGADO'),
        ('POR PAGAR', 'POR PAGAR')
    )

    nro_guia = models.CharField(max_length=10)
    ci_consignatario = models.CharField(max_length=12)
    nombre_consignatario = models.CharField(max_length=50)
    telefono_consignatario = models.CharField(max_length=12)
    tipo = models.CharField(max_length=10, choices=tipos, default='OTROS')
    cantidad = models.IntegerField(default=1)
    detalle = models.TextField()
    recibido = models.BooleanField(default=False)
    tipo_pago = models.CharField(max_length=10, choices=pagos, default='PAGADO')
    venta = models.OneToOneField(Venta, on_delete=models.CASCADE)


class Boleto(models.Model):
    plazas = models.IntegerField(default=0)
    venta = models.OneToOneField(Venta, on_delete=models.CASCADE)


class Dosificacion(models.Model):
    codigo_autorizacion = models.BigIntegerField()
    llave = models.CharField(max_length=128)
    factura_inicio = models.IntegerField()
    factura_fin = models.IntegerField()
    fecha_limite = models.DateField()
    activo = models.BooleanField(default=True)
    lugar = models.ForeignKey(Lugar, on_delete=models.CASCADE)


class Factura(models.Model):
    numero = models.IntegerField()
    ci_nit = models.CharField(max_length=12)
    nombre = models.CharField(max_length=50)
    fecha_hora = models.DateTimeField(default=datetime.datetime.now)
    importe = models.FloatField(default=0)
    venta = models.OneToOneField(Venta, on_delete=models.CASCADE)
    dosificacion = models.ForeignKey(Dosificacion, on_delete=models.CASCADE)

ventas/forms.py
import datetime
from .models import Cliente, Venta, Boleto, Envio, Lista, Dosificacion
from main.models import Persona
from django import forms
from django.db.models import Max
from django.forms import ModelForm, ValidationError
from django.contrib.auth import authenticate
from main.models import Usuario


class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = ['ci_nit', 'nombre', 'cel']
        widgets = {
            'ci_nit': forms.TextInput(attrs={'class': 'form-control only-numbers'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control only-letters upper'}),
            'cel': forms.NumberInput(attrs={'class': 'form-control only-numbers'}),
        }

    def clean_ci_nit(self):
        ci = self.cleaned_data.get('ci_nit')
        try:
            persona = Persona.objects.get(ci=ci)
        except (Persona.DoesNotExist, Persona.MultipleObjectsReturned) as e:
            persona = None
        if persona is not None:
            raise ValidationError('CI pertenece a un usuario del sistema')
        return ci


class VentaForm(ModelForm):
    class Meta:
        model = Venta
        fields = ['origen', 'destino', 'total']
        widgets = {
            'origen': forms.TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'destino': forms.Select(attrs={'class': 'form-control'}),
            'total': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def clean_destino(self):
        origen = self.cleaned_data.get('origen')
        destino = self.cleaned_data.get('destino')
        try:
            item = Lista.objects.filter(origen=origen,
                                         destino=destino,
                                         activo=True,
                                         fecha=datetime.date.today()).order_by('orden')[0:1].get()
            return destino
        except Lista.DoesNotExist:
            raise ValidationError('No existe ningun conductor con el destino seleccionado')

    def save(self, commit=True):
        origen = self.cleaned_data.get('origen')
        destino = self.cleaned_data.get('destino')
        venta = super().save(commit=False)
        item = Lista.objects.filter(origen=origen,
                                    destino=destino,
                                    activo=True,
                                    fecha=datetime.date.today()).order_by('orden')[0:1].get()
        venta.lista = item
        if commit:
            venta.save()
        return venta


class BoletoForm(ModelForm):
    class Meta:
        model = Boleto
        fields = ['plazas']
        widgets = {
            'plazas': forms.NumberInput(attrs={'class': 'form-control'})
        }


class EnvioForm(ModelForm):
    class Meta:
        model = Envio
        fields = ['ci_consignatario', 'nombre_consignatario', 'telefono_consignatario', 'tipo', 'cantidad', 'detalle', 'tipo_pago']
        widgets = {
            'ci_consignatario': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre_consignatario': forms.TextInput(attrs={'class': 'form-control upper'}),
            'telefono_consignatario': forms.NumberInput(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'}),
            'tipo': forms.Select(attrs={'class': 'form-control'}),
            'detalle': forms.Textarea(attrs={'class': 'form-control upper', 'rows': 2}),
            'tipo_pago': forms.RadioSelect(attrs={'class': 'icheck'})
        }


class RegistroAfiliadoForm(forms.Form):
    usuario = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    huella = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'disabled': True}))
    clave = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    destino = forms.CharField(widget=forms.Select(attrs={'class': 'form-control'}))

    def clean_clave(self):
        username = self.cleaned_data.get('usuario')
        clave = self.cleaned_data.get('clave')
        huella = self.cleaned_data.get('huella')
        user = self.get_user(username, clave, huella)
        if user is None:
            raise ValidationError('Credenciales incorrectas')
        if not hasattr(user, 'afiliado'):
            raise ValidationError('Usuario no es afiliado')
        if user.afiliado.estado == 'LICENCIA' or user.afiliado.estado == 'SUSPENDIDO':
            raise ValidationError('Usted no esta habilitado para ingresar a la lista')
        if not hasattr(user.afiliado, 'automovil'):
            raise ValidationError('El afiliado no tiene un vehiculo asignado')
        item = Lista.objects.filter(fecha=datetime.date.today(), afiliado=user.afiliado,
                                    automovil=user.afiliado.automovil, activo=True)
        if item.exists():
            raise ValidationError('El afiliado esta registrado en la lista')
        return clave

    def get_user(self, username, clave, huella):
        user = authenticate(username=username, password=clave)
        if user is None:
            try:
                user = Usuario.objects.get(usuario=username, codigo_huella=huella)
                return user
            except (Usuario.DoesNotExist, Usuario.MultipleObjectsReturned) as e:
                return None
        return user

    def save(self, commit=True):
        item = Lista()
        username = self.cleaned_data.get('usuario')
        huella = self.cleaned_data.get('huella')
        clave = self.cleaned_data.get('clave')
        destino = self.cleaned_data.get('destino')
        user = self.get_user(username, clave, huella)
        item.afiliado = user.afiliado
        item.automovil = user.afiliado.automovil
        item.destino = destino
        max = Lista.objects.filter(fecha=datetime.date.today()).aggregate(Max('orden'))
        if max['orden__max'] is None:
            item.orden = 1
        else:
            item.orden = max['orden__max'] + 1
        if commit:
            item.save()
        return item


class DosificacionForm(ModelForm):
    fecha_limite2 = forms.DateField(widget=forms.DateInput(format="%m/%d/%Y", attrs={'class': 'form-control datepicker'}))
    factura_inicio2 = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control only-numbers'}))
    factura_fin2 = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control only-numbers'}))
    codigo_autorizacion2 = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control only-numbers'}))
    llave2 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Dosificacion
        fields = ['lugar', 'fecha_limite', 'factura_inicio', 'factura_fin', 'codigo_autorizacion', 'llave']
        widgets = {
            'lugar': forms.Select(attrs={'class': 'form-control'}),
            'fecha_limite': forms.DateInput(format="%m/%d/%Y", attrs={'class': 'form-control datepicker'}),
            'factura_inicio': forms.NumberInput(attrs={'class': 'form-control only-numbers'}),
            'factura_fin': forms.NumberInput(attrs={'class': 'form-control only-numbers'}),
            'codigo_autorizacion': forms.NumberInput(attrs={'class': 'form-control only-numbers'}),
            'llave': forms.TextInput(attrs={'class': 'form-control'})
        }

    def clean_fecha_limite2(self):
        fechalimite2 = self.cleaned_data.get('fecha_limite2')
        fechalimite = self.cleaned_data.get('fecha_limite')
        if fechalimite != fechalimite2:
            raise ValidationError('Debe ser igual a la fecha limite')
        return fechalimite2

    def clean_factura_inicio2(self):
        factura_inicio = self.cleaned_data.get('factura_inicio')
        factura_inicio2 = self.cleaned_data.get('factura_inicio2')
        if factura_inicio != factura_inicio2:
            raise ValidationError('Debe ser igual a la factura inicio')
        return factura_inicio2

    def clean_factura_fin2(self):
        factura_inicio = self.cleaned_data.get('factura_inicio')
        factura_fin = self.cleaned_data.get('factura_fin')
        factura_fin2 = self.cleaned_data.get('factura_fin2')
        if factura_fin != factura_fin2:
            raise ValidationError('Debe ser igual a la factura fin')
        if factura_fin2 <= factura_inicio:
            raise ValidationError('Debe ser mayor a la factura inicio')
        return factura_fin2

    def clean_codigo_autorizacion2(self):
        codigo_autorizacion = self.cleaned_data.get('codigo_autorizacion')
        codigo_autorizacion2 = self.cleaned_data.get('codigo_autorizacion2')
        print(codigo_autorizacion)
        print(codigo_autorizacion2)
        if codigo_autorizacion != codigo_autorizacion2:
            raise ValidationError('Debe ser igual al codigo de autorizacion')
        return codigo_autorizacion2

    def clean_llave2(self):
        llave = self.cleaned_data.get('llave')
        llave2 = self.cleaned_data.get('llave2')
        if llave != llave2:
            raise ValidationError('Debe ser igual al codigo de llave de dosificacion')
        return llave2

ventas/templates/lista_agregar.html
{% extends "main_layout.html" %}

{% block styles %}
{% endblock %}

{% block main_title %}
Agregar afiliado a la lista
{% endblock %}

{% block content  %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <a href="{% url 'ventas.lista_conductores'%}" ><i class="fa fa-arrow-left"></i> Volver</a>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a href="#" ><i class="fa fa-wrench"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form class="form-horizontal" method="POST">
                    {% csrf_token %}
                    <div class="form-group" id="username">
                        <label for="{{form.usuario.id_for_label}}" class="control-label col-xs-3">USUARIO *</label>
                        <div class="col-xs-6">
                            {{form.usuario}}
                            {% if form.usuario.errors %}
                            <span class="text-danger">{{form.usuario.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="text-center" id="finger-panel" style="margin-bottom: 5px">
                        <span class="fa-stack fa-4x" id="finger-stack">
                            <i class="fas fa-fingerprint fa-stack-2x"></i>
                        </span>
                    </div>

                    <div class="form-group" id="clave">
                        <label for="{{form.clave.id_for_label}}" class="control-label col-xs-3">PASSWORD *</label>
                        <div class="col-xs-6">
                            <input type="hidden" name="clave" disabled>
                            {{form.clave}}
                            {{form.huella}}
                            {% if form.clave.errors %}
                            <span class="text-danger">{{form.clave.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-group" id="destino">
                        <label for="{{form.destino.id_for_label}}" class="control-label col-xs-3">DESTINO *</label>
                        <div class="col-xs-6">
                            {{form.destino}}
                            {% if form.destino.errors %}
                            <span class="text-danger">{{form.destino.errors|first}}</span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-xs-offset-3 col-xs-6">
                            <a href="{% url 'ventas.lista_conductores'%}" class="btn btn-default" id="btn-close"><i class="fa fa-arrow-left"></i> Volver</a>
                            <button type="button" class="btn btn-default" id="btn-cancel">
                                <i class="fa fa-close"></i> Cancelar
                            </button>
                            <button type="button" class="btn btn-primary pull-right" id="btn-next">
                                <i class="fa fa-arrow-right"></i> Siguiente
                            </button>
                            <button type="submit" class="btn btn-primary pull-right" id="btn-submit">
                                <i class="fa fa-check"></i> Ingresar
                            </button>
                        </div>
                    </div>
                </form> 
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
    {% load static %}
    <script>
        $(function(){
            var ws;
            {% if form.clave.errors %}
                showCredentials();
            {% else %}
                showUsername();
            {% endif %}

            $("#id_usuario").keypress(function(e){
                if(e.keyCode==13)
                    e.preventDefault();
            });

            $("#btn-next").on("click", function(e){
                if($("#username").find("input").val().length > 0){
                    var usuario = $("#username").find("input").eq(0).val();
                    $.ajax({
                        url: '{% url "lista.get_usuario" %}',
                        method: 'get',
                        data: {usuario},
                        beforeSend: function(){
                            $("form").find("span.text-danger").remove();
                            $("#clave input").val("");
                        },
                        success: function(data){
                            if(data.success){
                                var fingerprint = data.codigo_huella;
                                $("#id_huella").val(fingerprint);
                                showCredentials();
                            }else{
                                closeConnection();
                                var $error = $("<span>", {
                                    'class': 'text-danger',
                                    'text': data.message
                                });
                                $("#username").find("div").append($error);
                            }
                        },
                        error: function(){
                            closeConnection();
                            var $error = $("<span>", {
                                'class': 'text-danger',
                                'text': 'Un error ha ocurrido.'
                            });
                            $("#username").find("div").append($error);
                        }
                    });

                }
            });

            $("#btn-cancel").on("click", function(){
                showUsername();
            });

            function showUsername(){
                $("#username, #destino, #btn-next, #btn-close").show();
                $("#clave, #btn-submit, #btn-cancel, #finger-panel").hide();
                closeConnection();
                $("#id_clave").show();
                $("#id_clave").closest(".form-group").find("label").show();
                //$("form").find("span.text-danger").remove();
            }

            function showCredentials(){
                $("#username, #destino, #btn-next, #btn-close").hide();
                $("#clave, #btn-submit, #btn-cancel, #finger-panel").show();
                var fingerprint = $("#id_huella").val();
                if(fingerprint){
                    openConnection(fingerprint);
                    $("#id_clave").hide();
                    $("#id_clave").closest(".form-group").find("label").hide();
                }

                //$("form").find("span.text-danger").remove();
            }

            function openConnection(fingerprint){
                ws = new WebSocket("ws://localhost:9090/finger/finger");
                ws.onopen = function(){
                    console.log("ws connection open...");
                    var data = {
                        type: "prepare-verify",
                        data: fingerprint
                    };
                    ws.send(JSON.stringify(data));
                };

                ws.onmessage = function(evt){
                    var response = JSON.parse(evt.data);
                    var type = response.type;
                    //console.log(response);
                    switch(type){
                        case 'verify-response':
                            $("#finger-stack i.fa-check, #finger-stack i.fa-close").remove();
                            var success = response.success;
                            var $icon = $("<i class='fas fa-check fa-stack-1x' style='color:green'></i>").hide();
                            if(success){
                                $("#finger-stack").append($icon);
                                $("#id_huella").prop("disabled", false);
                                $("form").submit();
                            }else{
                                $icon = $("<i class='fas fa-close fa-stack-1x' style='color:red'></i>").hide();
                                $("#finger-stack").append($icon);
                                closeConnection();
                                openConnection(fingerprint);
                            }
                            $icon.show('fast');
                        break;
                    }
                }

                ws.onclose = function(){
                    console.log("ws connection closed");
                }
            }

            function closeConnection(){
                if(ws)
                    ws.close();
            }
        });
    </script>
{% endblock %}

ventas/templates/sin_dosificacion.html
{% extends "main_layout.html" %}

{% block main_title %}
Sin dosificacion
{% endblock %}

{% block content  %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Sin dosificacion</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a href="#" ><i class="fa fa-wrench"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                
            </div>
        </div>
    </div>
</div>
{% endblock  %}

ventas/templates/venta_boletos.html
{% extends "main_layout.html" %}

{% block styles%}
{% load static%}
{% endblock %}

{% block main_title %}
Venta de boletos
{% endblock %}

{% block content  %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a href="#" ><i class="fa fa-wrench"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
            <form class="form-horizontal" method="POST">
                {% csrf_token %}
                <span class="section">Informacion de cliente</span>
                <div class="form-group">
                    <label for="{{cliente_form.ci_nit.id_for_label}}" class="control-label col-xs-3">CI / NIT *</label>
                    <div class="col-xs-6">
                        <div class="input-group">
                            {{cliente_form.ci_nit}}
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary" id="btn-search">
                                    <i class="fa fa-search"></i> Buscar
                                </button>
                            </div>
                        </div>
                        {% if cliente_form.ci_nit.errors %}
                        <span class="text-danger">{{cliente_form.ci_nit.errors|first}}</span>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{cliente_form.nombre.id_for_label}}" class="control-label col-xs-3">NOMBRE *</label>
                    <div class="col-xs-6">
                        {{cliente_form.nombre}}
                        {% if cliente_form.nombre.errors %}
                        <span class="text-danger">{{cliente_form.nombre.errors|first}}</span>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{cliente_form.cel.id_for_label}}" class="control-label col-xs-3">TELEFONO *</label>
                    <div class="col-xs-6">
                        {{cliente_form.cel}}
                        {% if cliente_form.cel.errors %}
                        <span class="text-danger">{{cliente_form.cel.errors|first}}</span>
                        {% endif %}
                    </div>
                </div>
                <span class="section">Informacion de venta</span>

                <div class="form-group">
                    <label for="{{venta_form.origen.id_for_label}}" class="control-label col-xs-3">ORIGEN *</label>
                    <div class="col-xs-6">
                        {{venta_form.origen}}
                        {% if venta_form.origen.errors %}
                        <span class="text-danger">{{venta_form.origen.errors|first}}</span>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{venta_form.destino.id_for_label}}" class="control-label col-xs-3">DESTINO *</label>
                    <div class="col-xs-6">
                        {{venta_form.destino}}
                        {% if venta_form.destino.errors %}
                        <span class="text-danger">{{venta_form.destino.errors|first}}</span>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{boleto_form.plazas.id_for_label}}" class="control-label col-xs-3">ASIENTOS *</label>
                    <div class="col-xs-6">
                        {{boleto_form.plazas}}
                        {% if boleto_form.plazas.errors %}
                        <span class="text-danger">{{boleto_form.plazas.errors|first}}</span>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{venta_form.total.id_for_label}}" class="control-label col-xs-3">PRECIO *</label>
                    <div class="col-xs-6">
                        {{venta_form.total}}
                        {% if venta_form.total.errors %}
                        <span class="text-danger">{{venta_form.total.errors|first}}</span>
                        {% endif %}
                    </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-xs-offset-3 col-xs-6">
                        <button type="submit" class="btn btn-primary pull-right">
                            <i class="fa fa-save"></i> Guardar
                        </button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
{% load static %}
<script>
    $(function(){
        $("#btn-search").on("click", function(){
            var $btn = $(this);
            var ci = $btn.closest(".form-group").find("input").first().val();
            $.ajax({
                url: '{% url "ventas.clientes" %}',
                method: 'get',
                data: {ci: ci},
                beforeSend: function(){
                    $btn.find("i").removeClass("fa-search").addClass("fa-spinner fa-spin");
                    $("#id_nombre").val("");
                    $("#id_cel").val("");
                },
                success: function(data){
                    $("#id_ci_nit").val(data.ci);
                    $("#id_nombre").val(data.nombre);
                    $("#id_cel").val(data.cel);
                },
                complete: function(){
                    $btn.find("i").addClass("fa-search").removeClass("fa-spinner fa-spin");
                }
            });
        });
    });
</script>
{% endblock %}